# Generated by Django 5.2.8 on 2025-11-18 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastLanguage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(blank=True, default="pt", max_length=10, null=True)),
                ("name", models.CharField(blank=True, default="português", max_length=60, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PopularTerm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("term", models.CharField(db_index=True, max_length=255)),
                ("times", models.IntegerField(default=1)),
                ("date_search", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TopicSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_recorded", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("feed", models.URLField(unique=True)),
                ("image", models.CharField(blank=True, default="/static/dist/img/podcast-banner.png", max_length=255, null=True)),
                ("total_episodes", models.IntegerField(default=0)),
                ("language", models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to="podcasts.podcastlanguage")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=1024)),
                ("link", models.URLField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("published", models.DateTimeField(blank=True, null=True)),
                ("enclosure", models.CharField(blank=True, max_length=1024, null=True)),
                ("to_json", models.JSONField(blank=True, null=True)),
                ("podcast", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="episodes", to="podcasts.podcast")),
                ("tags", models.ManyToManyField(blank=True, related_name="episodes", to="podcasts.tag")),
            ],
        ),
    ]
