# Generated by Django 5.2.11 on 2026-02-28 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_add_search_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularterm',
            name='date_search',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
