# Generated by Django 5.2.14 on 2026-06-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_alter_popularterm_date_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicSuggestion',
        ),
    ]
