engines:
  pep8:
    enabled: true
  radon:
    enabled:
  duplication:
    enabled: true
    config:
      languages:
        - python
exclude_paths:
- "migrations/"
- "celerybeat-schedule"
- "app/static/src/js/lib"
- "app/static/node_modules"
- "app/static/dist"