doc-warnings: false
test-warnings: false
strictness: medium
max-line-length: 120
uses:
  - flask
autodetect: true
ignore-paths:
  - migrations        
requirements:
  - requirements.txt
python-targets:
  - 3
