# Generated by Django 2.0 on 2017-12-19 20:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('published_at', models.DateField(blank=True, verbose_name='published at')),
                ('permalink', models.URLField(verbose_name='permalink')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, size=None)),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'db_table': 'episode',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('feed', models.URLField(unique=True, verbose_name='feed')),
                ('image', models.CharField(default='/static/dist/img/podcast-banner.png', max_length=200, verbose_name='thumbnail')),
                ('last_feed_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last update')),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
                'db_table': 'podcast',
            },
        ),
        migrations.CreateModel(
            name='PopularTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('term', models.TextField(verbose_name='Term searched')),
                ('times', models.IntegerField(default=1, verbose_name='number of times')),
                ('date_search', models.DateTimeField(auto_now_add=True, verbose_name='Date of search')),
            ],
            options={
                'verbose_name': 'Popular Term',
                'verbose_name_plural': 'Popular Terms',
                'db_table': 'popular_term',
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='core.Podcast'),
        ),
    ]
