"""empty message

Revision ID: 074e1c1a8ba9
Revises: None
Create Date: 2016-04-06 11:05:17.565210

"""

# revision identifiers, used by Alembic.
revision = '074e1c1a8ba9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('feed', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('podcast')
    ### end Alembic commands ###
