"""empty message

Revision ID: 094ef5ae04e9
Revises: 358d9bf8f69a
Create Date: 2016-05-04 21:31:06.305069

"""

# revision identifiers, used by Alembic.
revision = '094ef5ae04e9'
down_revision = '358d9bf8f69a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('to_json', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'to_json')
    ### end Alembic commands ###
