"""empty message

Revision ID: 0c2841d4cfcd
Revises: 34d97cbc759e
Create Date: 2016-07-28 20:19:00.866339

"""

# revision identifiers, used by Alembic.
revision = '0c2841d4cfcd'
down_revision = '34d97cbc759e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
