"""empty message

Revision ID: 32dc1b7c443a
Revises: a4e76c6edc38
Create Date: 2016-09-17 11:42:51.495569

"""

# revision identifiers, used by Alembic.
revision = '32dc1b7c443a'
down_revision = 'a4e76c6edc38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('total_episodes', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'total_episodes')
    ### end Alembic commands ###
