"""empty message

Revision ID: 358d9bf8f69a
Revises: a86dedc20d0a
Create Date: 2016-05-03 22:12:18.455148

"""

# revision identifiers, used by Alembic.
revision = '358d9bf8f69a'
down_revision = 'a86dedc20d0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_episode_link'), 'episode', ['link'], unique=True)
    op.drop_constraint('episode_link_key', 'episode', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('episode_link_key', 'episode', ['link'])
    op.drop_index(op.f('ix_episode_link'), table_name='episode')
    op.alter_column('episode', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
