"""empty message

Revision ID: 8097d3d0862a
Revises: d3ebb90af68a
Create Date: 2016-06-19 15:14:23.090285

"""

# revision identifiers, used by Alembic.
revision = '8097d3d0862a'
down_revision = 'd3ebb90af68a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('popular_term', sa.Column('date_search', sa.Date(), nullable=True))
    op.create_index(op.f('ix_popular_term_date_search'), 'popular_term', ['date_search'], unique=False)
    op.drop_index('ix_popular_term_term', table_name='popular_term')
    op.create_index(op.f('ix_popular_term_term'), 'popular_term', ['term'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_popular_term_term'), table_name='popular_term')
    op.create_index('ix_popular_term_term', 'popular_term', ['term'], unique=True)
    op.drop_index(op.f('ix_popular_term_date_search'), table_name='popular_term')
    op.drop_column('popular_term', 'date_search')
    ### end Alembic commands ###
