"""empty message

Revision ID: 8ce18fd9945a
Revises: 012722a93d11
Create Date: 2016-07-08 12:49:02.721861

"""

# revision identifiers, used by Alembic.
revision = '8ce18fd9945a'
down_revision = '012722a93d11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('topic_suggestion_podcast_id_fkey', 'topic_suggestion', type_='foreignkey')
    op.drop_column('topic_suggestion', 'podcast_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_suggestion', sa.Column('podcast_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('topic_suggestion_podcast_id_fkey', 'topic_suggestion', 'podcast', ['podcast_id'], ['id'])
    ### end Alembic commands ###
