"""empty message

Revision ID: 95b81f5e2452
Revises: e954ba3207a3
Create Date: 2016-08-22 20:26:36.349286

"""

# revision identifiers, used by Alembic.
revision = '95b81f5e2452'
down_revision = 'e954ba3207a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcast_language_id'), 'podcast_language', ['id'], unique=False)
    op.add_column('podcast', sa.Column('language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'podcast', 'podcast_language', ['language_id'], ['id'])
    op.drop_column('podcast', 'language')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('language', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'podcast', type_='foreignkey')
    op.drop_column('podcast', 'language_id')
    op.drop_index(op.f('ix_podcast_language_id'), table_name='podcast_language')
    op.drop_table('podcast_language')
    ### end Alembic commands ###
