"""empty message

Revision ID: a2cee6d25d2f
Revises: 074e1c1a8ba9
Create Date: 2016-04-06 11:34:28.093412

"""

# revision identifiers, used by Alembic.
revision = 'a2cee6d25d2f'
down_revision = '074e1c1a8ba9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('podcast', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'updated_at')
    op.drop_column('podcast', 'created_at')
    ### end Alembic commands ###
