"""empty message

Revision ID: a86dedc20d0a
Revises: 13664b2b8ad9
Create Date: 2016-04-24 20:33:24.624443

"""

# revision identifiers, used by Alembic.
revision = 'a86dedc20d0a'
down_revision = '13664b2b8ad9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
