"""empty message

Revision ID: d3ebb90af68a
Revises: a331c8728f7f
Create Date: 2016-06-18 17:01:21.796256

"""

# revision identifiers, used by Alembic.
revision = 'd3ebb90af68a'
down_revision = 'a331c8728f7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('times', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_popular_term_term'), 'popular_term', ['term'], unique=True)
    op.add_column('tag', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'updated_at')
    op.drop_column('tag', 'created_at')
    op.drop_index(op.f('ix_popular_term_term'), table_name='popular_term')
    op.drop_table('popular_term')
    ### end Alembic commands ###
