"""empty message

Revision ID: dde8a74cfffa
Revises: 0c2841d4cfcd
Create Date: 2016-07-29 17:42:17.142867

"""

# revision identifiers, used by Alembic.
revision = 'dde8a74cfffa'
down_revision = '0c2841d4cfcd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('language', sa.String(length=5), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'language')
    ### end Alembic commands ###
